name: "adventureArena"
main: "adventureArena.AdventureArena"
version: "1.0"
depend: []

commands:
   joinMiniGameHub:
      usage: /joinMiniGameHub <player> [x y z]
   leaveMiniGameHub:
      usage: /leaveMiniGameHub <player> [x y z]
   serverinfo:
      usage: /serverinfo
