name: "adventureArena"
main: "adventureArena.AdventureArena"
version: "1.0"
depend: []

commands:
   saveInventory:
      usage: /saveInventory <player>
   restoreInventory:
      usage: /restoreInventory <player>
   enableDigging:
      usage: /enableDigging <player>
   disableDigging:
      usage: /disableDigging <player>
      